// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('creertache', function() {
  jest.setTimeout(5000) //I put jest because this.timeout does not work
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('creertache', async function() {
    // Test name: creertache
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 772x692 | 
    await driver.manage().window().setRect({ width: 772, height: 692 })
    // 3 | click | linkText=Add | 
    await driver.findElement(By.linkText("Add")).click()
    // 4 | click | id=title | 
    await driver.findElement(By.id("title")).click()
    // 5 | type | id=title | testtest
    await driver.findElement(By.id("title")).sendKeys("testtest")
    // 6 | click | id=description | 
    await driver.findElement(By.id("description")).click()
    // 7 | type | id=description | testtest
    await driver.findElement(By.id("description")).sendKeys("testtest")
    // 8 | click | css=.btn | 
    await driver.findElement(By.css(".btn")).click()
  })
})
